"""In-memory data store. No database — state lives in process memory and
resets on restart, consistent with the rest of this project's mocked approach."""

import uuid
from dataclasses import dataclass, field
from datetime import datetime, timezone

from app.models import (
    Customer,
    Deal,
    DiscountChangeEntry,
    DiscountHistoryEntry,
    DiscountRecommendation,
    LineItem,
)

# A proposal within this many points of the AI's recommendation auto-applies;
# beyond it, the line locks and waits for a manager to approve or reject it.
AUTO_APPROVE_BAND_PCT = 3.0


class LineItemLockedError(Exception):
    """Raised when an action targets a line item that's pending manager approval."""
from app.seed_data import (
    ATLAS_CUSTOMER,
    ATLAS_DEAL,
    ATLAS_HISTORY,
    ATLAS_LINE_ITEMS,
    CERULEAN_CUSTOMER,
    CERULEAN_DEAL,
    CERULEAN_HISTORY,
    CERULEAN_LINE_ITEMS,
    MERIDIAN_CUSTOMER,
    MERIDIAN_DEAL,
    MERIDIAN_HISTORY,
    MERIDIAN_LINE_ITEMS,
    NORTHWIND_CUSTOMER,
    NORTHWIND_DEAL,
    NORTHWIND_HISTORY,
    NORTHWIND_LINE_ITEMS,
)


class NotFoundError(Exception):
    pass


@dataclass
class DealState:
    deal: Deal
    customer: Customer
    discount_history: list[DiscountHistoryEntry]
    line_items: dict[str, LineItem] = field(default_factory=dict)
    recommendations: dict[str, DiscountRecommendation] = field(default_factory=dict)
    approval_history: list[tuple[str | None, str | None]] = field(default_factory=list)
    # One undo stack per line item, mirroring approval_history above — a
    # snapshot of the decision-related fields is pushed before every mutation
    # in decide_line_item / resolve_line_item_approval, so either the rep's
    # or the manager's most recent action on that line can be popped off.
    line_item_snapshots: dict[str, list[dict]] = field(default_factory=dict)
    # Line items whose recommendation has already been generated by Claude
    # this server run. Generation happens lazily on first real page load
    # (not on every background refetch) and is cached here afterward — the
    # number must stay put once a rep is looking at it, not shift under
    # them because React Query silently refetched on window focus.
    ai_generated_line_items: set[str] = field(default_factory=set)


def _net_value(deal_value: float, pct: float) -> float:
    return round(deal_value * (1 - pct / 100), 2)


def generate_recommendation(line_item_id: str, category: str, value: float) -> DiscountRecommendation:
    """Deterministic mock "AI" generation, mirroring generateRecommendation() in
    frontend/src/lib/deal-data.ts."""
    size_tier = 3.0 if value >= 250_000 else 2.0 if value >= 100_000 else 1.5 if value >= 50_000 else 1.0
    pressure = 4.0 if category == "Services" else 3.0 if category == "Networking" else 1.5

    factors = [
        {"name": "Baseline (segment: Enterprise)", "contribution_pct": 8.0, "positive": True},
        {"name": "Customer tenure (4 yrs)", "contribution_pct": 2.5, "positive": True},
        {"name": "Deal size tier", "contribution_pct": size_tier, "positive": True},
        {"name": "Regional competitive pressure", "contribution_pct": pressure, "positive": True},
        {"name": "Margin floor guardrail", "contribution_pct": -2.0, "positive": False},
    ]
    discount = round(sum(f["contribution_pct"] for f in factors) * 10) / 10
    confidence = "high" if discount <= 12 else "medium" if discount <= 14 else "low"

    return DiscountRecommendation(
        line_item_id=line_item_id,
        recommended_pct=discount,
        confidence=confidence,
        net_value=_net_value(value, discount),
        factors=factors,
    )


class DataStore:
    def __init__(self) -> None:
        self.deals: dict[str, DealState] = {}
        self._seed()

    def _seed(self) -> None:
        try:
            self._seed_from_supabase()
        except Exception as exc:  # noqa: BLE001 - a data-source hiccup must not take the app down
            print(f"[store] Supabase seed unavailable ({exc}); falling back to seed_data.py")
            self._seed_from_literals()

    def _seed_from_supabase(self) -> None:
        from app.supabase_data import load_deal_states

        for deal, customer, history, line_items, rec_specs in load_deal_states():
            state = DealState(
                deal=deal.model_copy(deep=True),
                customer=customer.model_copy(deep=True),
                discount_history=[h.model_copy() for h in history],
            )
            for li in line_items:
                state.line_items[li.id] = li.model_copy(deep=True)
                rec = rec_specs.get(li.id)
                if not rec:
                    continue
                state.recommendations[li.id] = DiscountRecommendation(
                    line_item_id=li.id,
                    recommended_pct=rec["recommended_pct"],
                    confidence=rec["confidence"],
                    net_value=_net_value(li.deal_value, rec["recommended_pct"]),
                    factors=[f.model_copy() for f in rec["factors"]],
                )
            self.deals[deal.id] = state
        if not self.deals:
            raise RuntimeError("Supabase returned zero deals")
        print(f"[store] Seeded {len(self.deals)} deals from Supabase")

    def _seed_from_literals(self) -> None:
        for deal, customer, history, line_item_specs in (
            (NORTHWIND_DEAL, NORTHWIND_CUSTOMER, NORTHWIND_HISTORY, NORTHWIND_LINE_ITEMS),
            (CERULEAN_DEAL, CERULEAN_CUSTOMER, CERULEAN_HISTORY, CERULEAN_LINE_ITEMS),
            (MERIDIAN_DEAL, MERIDIAN_CUSTOMER, MERIDIAN_HISTORY, MERIDIAN_LINE_ITEMS),
            (ATLAS_DEAL, ATLAS_CUSTOMER, ATLAS_HISTORY, ATLAS_LINE_ITEMS),
        ):
            state = DealState(
                deal=deal.model_copy(deep=True),
                customer=customer.model_copy(deep=True),
                discount_history=[h.model_copy() for h in history],
            )
            for line_item_id, category, value, recommended_pct, confidence, factors in line_item_specs:
                state.line_items[line_item_id] = LineItem(
                    id=line_item_id,
                    deal_id=deal.id,
                    product_category=category,
                    deal_value=value,
                    applied_discount_pct=None,
                    decision="pending",
                )
                state.recommendations[line_item_id] = DiscountRecommendation(
                    line_item_id=line_item_id,
                    recommended_pct=recommended_pct,
                    confidence=confidence,
                    net_value=_net_value(value, recommended_pct),
                    factors=[f.model_copy() for f in factors],
                )
            self.deals[deal.id] = state

    def get_deal_state(self, deal_id: str) -> DealState:
        state = self.deals.get(deal_id)
        if state is None:
            raise NotFoundError(f"Deal '{deal_id}' not found")
        return state

    def ensure_ai_recommendations(self, state: DealState) -> None:
        """Generates each pending line item's recommendation with Claude on
        first real access this session. No-ops (keeps the existing
        deterministic/Supabase value) if no API key is configured, the item
        is already decided, or generation was already done this run."""
        from app.config import settings

        if not settings.anthropic_api_key:
            return

        from app.ai_recommendation import generate_ai_recommendation

        for item in state.line_items.values():
            if item.id in state.ai_generated_line_items or item.decision != "pending":
                continue
            try:
                result = generate_ai_recommendation(item, state.customer, state.discount_history)
                state.recommendations[item.id] = DiscountRecommendation(
                    line_item_id=item.id,
                    recommended_pct=result["recommended_pct"],
                    confidence=result["confidence"],
                    net_value=_net_value(item.deal_value, result["recommended_pct"]),
                    factors=result["factors"],
                )
            except Exception as exc:  # noqa: BLE001 - a bad generation must never break the page
                print(f"[store] AI recommendation failed for {item.id} ({exc}); keeping existing value")
            finally:
                state.ai_generated_line_items.add(item.id)

    def blended_discount_pct(self, state: DealState) -> float:
        total_value = 0.0
        total_weighted = 0.0
        for item in state.line_items.values():
            effective = (
                item.applied_discount_pct
                if item.applied_discount_pct is not None
                else state.recommendations[item.id].recommended_pct
            )
            total_value += item.deal_value
            total_weighted += item.deal_value * effective
        if total_value == 0:
            return 0.0
        return round(total_weighted / total_value, 1)

    def create_deal(
        self,
        name: str,
        customer_name: str,
        term_length: str,
        region: str,
        product_categories: list[str],
    ) -> DealState:
        deal_id = f"deal-{uuid.uuid4().hex[:8]}"
        deal = Deal(
            id=deal_id,
            name=name,
            term_length=term_length,
            product_categories=product_categories,
            sample_deal_key=deal_id,
            status="within_range",
            approval_state=None,
            region=region,
        )
        # A brand-new deal has no track record yet — zeroed stats and an
        # empty history are the honest starting point, not placeholder data.
        customer = Customer(
            id=f"cust-{uuid.uuid4().hex[:8]}",
            name=customer_name,
            partner_since=datetime.now(timezone.utc).year,
            lifetime_value="$0",
            renewal_rate_pct=0.0,
            avg_discount_pct=0.0,
        )
        state = DealState(deal=deal, customer=customer, discount_history=[])
        self.deals[deal_id] = state
        return state

    def add_line_item(self, deal_id: str, product_category: str, deal_value: float) -> LineItem:
        state = self.get_deal_state(deal_id)
        line_item_id = f"line-{uuid.uuid4().hex[:8]}"
        item = LineItem(
            id=line_item_id,
            deal_id=deal_id,
            product_category=product_category,
            deal_value=deal_value,
            applied_discount_pct=None,
            decision="pending",
        )
        state.line_items[line_item_id] = item
        state.recommendations[line_item_id] = generate_recommendation(line_item_id, product_category, deal_value)
        return item

    def remove_line_item(self, deal_id: str, line_item_id: str) -> None:
        state = self.get_deal_state(deal_id)
        item = state.line_items.get(line_item_id)
        if item is None:
            raise NotFoundError(f"Line item '{line_item_id}' not found on deal '{deal_id}'")
        if item.line_approval_state == "pending_approval":
            raise LineItemLockedError(
                f"Line item '{line_item_id}' is awaiting manager approval and can't be removed"
            )
        del state.line_items[line_item_id]
        state.recommendations.pop(line_item_id, None)

    def update_line_item(
        self,
        deal_id: str,
        line_item_id: str,
        product_category: str | None,
        deal_value: float | None,
    ) -> LineItem:
        state = self.get_deal_state(deal_id)
        item = state.line_items.get(line_item_id)
        if item is None:
            raise NotFoundError(f"Line item '{line_item_id}' not found on deal '{deal_id}'")
        if item.line_approval_state == "pending_approval":
            raise LineItemLockedError(
                f"Line item '{line_item_id}' is awaiting manager approval and is locked until then"
            )
        if product_category is not None:
            item.product_category = product_category
        if deal_value is not None:
            item.deal_value = deal_value
        item.applied_discount_pct = None
        item.decision = "pending"
        item.override_reason = None
        item.decided_by = None
        state.recommendations[line_item_id] = generate_recommendation(
            line_item_id, item.product_category, item.deal_value
        )
        return item

    def _log(
        self,
        item: LineItem,
        by: str,
        previous_pct: float | None,
        new_pct: float | None,
        reason: str | None,
        action: str,
    ) -> None:
        item.history.append(
            DiscountChangeEntry(
                at=datetime.now(timezone.utc).isoformat(),
                by=by,
                previous_pct=previous_pct,
                new_pct=new_pct,
                reason=reason,
                action=action,
            )
        )

    def _snapshot_line_item(self, state: DealState, item: LineItem) -> None:
        state.line_item_snapshots.setdefault(item.id, []).append(
            {
                "decision": item.decision,
                "line_approval_state": item.line_approval_state,
                "applied_discount_pct": item.applied_discount_pct,
                "pending_discount_pct": item.pending_discount_pct,
                "override_reason": item.override_reason,
                "decided_by": item.decided_by,
                "history_len": len(item.history),
            }
        )

    def undo_line_item_decision(self, deal_id: str, line_item_id: str) -> LineItem:
        state = self.get_deal_state(deal_id)
        item = state.line_items.get(line_item_id)
        if item is None:
            raise NotFoundError(f"Line item '{line_item_id}' not found on deal '{deal_id}'")
        stack = state.line_item_snapshots.get(line_item_id)
        if not stack:
            raise NotFoundError(f"No decision to undo for line item '{line_item_id}'")
        snap = stack.pop()
        item.decision = snap["decision"]
        item.line_approval_state = snap["line_approval_state"]
        item.applied_discount_pct = snap["applied_discount_pct"]
        item.pending_discount_pct = snap["pending_discount_pct"]
        item.override_reason = snap["override_reason"]
        item.decided_by = snap["decided_by"]
        # Keep the visible history log in sync — otherwise it'd still show
        # the action that was just undone as if it happened.
        item.history = item.history[: snap["history_len"]]
        return item

    def decide_line_item(
        self,
        deal_id: str,
        line_item_id: str,
        action: str,
        applied_discount_pct: float | None,
        decided_by: str,
        reason: str | None = None,
    ) -> LineItem:
        state = self.get_deal_state(deal_id)
        item = state.line_items.get(line_item_id)
        if item is None:
            raise NotFoundError(f"Line item '{line_item_id}' not found on deal '{deal_id}'")
        if item.line_approval_state == "pending_approval":
            raise LineItemLockedError(
                f"Line item '{line_item_id}' already has a proposal awaiting manager approval"
            )

        self._snapshot_line_item(state, item)
        recommendation = state.recommendations[line_item_id]
        previous = item.applied_discount_pct
        item.decided_by = decided_by

        if action == "accept":
            item.applied_discount_pct = recommendation.recommended_pct
            item.decision = "accepted"
            item.line_approval_state = "none"
            item.override_reason = None
            item.pending_discount_pct = None
            self._log(item, decided_by, previous, item.applied_discount_pct, None, "accepted")
        else:  # propose
            assert applied_discount_pct is not None
            deviation = abs(applied_discount_pct - recommendation.recommended_pct)
            item.override_reason = reason
            if deviation <= AUTO_APPROVE_BAND_PCT:
                item.applied_discount_pct = applied_discount_pct
                item.decision = "adjusted"
                item.line_approval_state = "none"
                item.pending_discount_pct = None
                self._log(
                    item, decided_by, previous, applied_discount_pct, reason, "proposed_auto_applied"
                )
            else:
                item.decision = "overridden"
                item.line_approval_state = "pending_approval"
                item.pending_discount_pct = applied_discount_pct
                # applied_discount_pct is untouched — doesn't count toward the
                # blended discount until a manager approves it.
                self._log(
                    item, decided_by, previous, applied_discount_pct, reason, "proposed_pending_approval"
                )
        return item

    def resolve_line_item_approval(
        self, deal_id: str, line_item_id: str, decision: str, decided_by: str
    ) -> LineItem:
        state = self.get_deal_state(deal_id)
        item = state.line_items.get(line_item_id)
        if item is None:
            raise NotFoundError(f"Line item '{line_item_id}' not found on deal '{deal_id}'")
        if item.line_approval_state != "pending_approval":
            raise LineItemLockedError(f"Line item '{line_item_id}' has no proposal awaiting approval")

        self._snapshot_line_item(state, item)
        previous = item.applied_discount_pct
        proposed = item.pending_discount_pct
        if decision == "approved":
            item.applied_discount_pct = proposed
            item.line_approval_state = "approved"
            self._log(item, decided_by, previous, proposed, item.override_reason, "approved")
        else:
            item.line_approval_state = "rejected"
            item.decision = "pending"
            item.override_reason = None
            self._log(item, decided_by, previous, previous, None, "rejected")
        item.pending_discount_pct = None
        return item

    def set_approval(self, deal_id: str, decision: str, note: str | None = None) -> DealState:
        state = self.get_deal_state(deal_id)
        state.approval_history.append((state.deal.approval_state, state.deal.approval_note))
        state.deal.approval_state = decision
        state.deal.approval_note = note
        return state

    def undo_approval(self, deal_id: str) -> DealState:
        state = self.get_deal_state(deal_id)
        if not state.approval_history:
            raise NotFoundError(f"No approval decision to undo for deal '{deal_id}'")
        state.deal.approval_state, state.deal.approval_note = state.approval_history.pop()
        return state

    def send_quote(self, deal_id: str, recipient: str) -> DealState:
        state = self.get_deal_state(deal_id)
        state.deal.quote_sent_at = datetime.now(timezone.utc).isoformat()
        state.deal.quote_sent_to = recipient
        return state

    def undo_send_quote(self, deal_id: str) -> DealState:
        state = self.get_deal_state(deal_id)
        if state.deal.quote_sent_at is None:
            raise NotFoundError(f"Deal '{deal_id}' has not been sent")
        state.deal.quote_sent_at = None
        state.deal.quote_sent_to = None
        return state

    def line_progress(self, state: DealState) -> tuple[int, int]:
        """(decided, in_review): a line counts as decided once the rep has
        accepted or adjusted it and nothing is awaiting a manager; a rejected
        proposal resets the line to undecided, so it isn't counted here."""
        decided = 0
        in_review = 0
        for item in state.line_items.values():
            if item.line_approval_state == "pending_approval":
                in_review += 1
            elif item.decision != "pending":
                decided += 1
        return decided, in_review


store = DataStore()
