"""Generates the seed data in schema.sql.

Company names and dates come from Faker; every number that the recommendation
engine actually reasons about (discount percentages, outcomes, renewal rates)
is derived from a small set of per-customer "behavior" parameters below, not
randomized independently — otherwise the seeded discount history wouldn't
correlate with win/loss the way real account behavior does, and the AI
factors ("why this number") would have nothing believable to point at.

Run with `python generate_seed_data.py` to print the SQL to stdout. The
checked-in schema.sql is the reviewed, hand-tuned output of a run of this
script — regenerating will reshuffle names/dates but keep the same shape.
"""

import random

from faker import Faker

fake = Faker()
Faker.seed(7)
random.seed(7)

PRODUCT_CATEGORIES = ["Compute", "Storage", "Networking", "Services"]
TERM_LENGTHS = ["12mo", "24mo", "36mo"]
REGIONS = ["north_america", "uk", "eurozone", "japan", "india", "brazil"]

# One row per customer "archetype": how they tend to behave in negotiations.
# win_rate and discount_spread drive a *consistent* discount_history, so a
# high-win_rate customer's history shows they win even at higher discounts,
# and a low-win_rate one shows losses even at modest ones — the same signal
# the "why this number" factors and the AI take reason about downstream.
ARCHETYPES = [
    {"segment": "Enterprise", "win_rate": 0.85, "baseline": 8.0, "avg_discount": 10.5, "n_deals": 4},
    {"segment": "Mid-market", "win_rate": 0.55, "baseline": 10.0, "avg_discount": 13.5, "n_deals": 4},
    {"segment": "Enterprise", "win_rate": 0.95, "baseline": 7.0, "avg_discount": 9.0, "n_deals": 6},
    {"segment": "Mid-market", "win_rate": 0.65, "baseline": 10.0, "avg_discount": 13.0, "n_deals": 6},
]


def gen_customer(customer_id: str, archetype: dict, partner_since: int) -> dict:
    company = fake.company().replace(",", "")
    return {
        "id": customer_id,
        "name": company,
        "partner_since": partner_since,
        "lifetime_value": f"${random.randint(300, 3400)}K" if random.random() > 0.3 else f"${random.uniform(1.0, 3.5):.2f}M",
        "renewal_rate_pct": round(archetype["win_rate"] * 100),
        "avg_discount_pct": archetype["avg_discount"],
        "segment": archetype["segment"],
    }


def gen_discount_history(customer_id: str, archetype: dict, start_year: int) -> list[dict]:
    """A discount history where the outcome is a function of how far the
    ask sat above this customer's baseline — not independent random noise."""
    rows = []
    date = fake.date_between(start_date=f"-{2026 - start_year}y", end_date="-6m")
    for i in range(archetype["n_deals"]):
        drift = random.uniform(-1.5, 3.5)
        pct = round(max(archetype["baseline"], archetype["avg_discount"] + drift), 1)
        # Further above baseline -> more likely lost, weighted by this
        # customer's overall win_rate archetype.
        lose_chance = min(0.9, max(0.05, (pct - archetype["avg_discount"]) / 6 + (1 - archetype["win_rate"])))
        outcome = "lost" if random.random() < lose_chance else "won"
        rows.append({"customer_id": customer_id, "date": date.strftime("%b %Y"), "discount_pct": pct, "outcome": outcome})
        date = fake.date_between(start_date=date, end_date="+8m")
    return rows


def gen_deal(deal_id: str, customer: dict) -> dict:
    n_lines = random.randint(2, 3)
    categories = random.sample(PRODUCT_CATEGORIES, n_lines)
    return {
        "id": deal_id,
        "name": f"{customer['name']} — {fake.bs().title()}",
        "customer_id": customer["id"],
        "term_length": random.choice(TERM_LENGTHS),
        "product_categories": categories,
        "region": random.choice(REGIONS),
    }


if __name__ == "__main__":
    print("-- Generated by generate_seed_data.py (Faker(seed=7)) — see schema.sql for the reviewed, checked-in version.")
    for n, archetype in enumerate(ARCHETYPES, start=1):
        customer = gen_customer(f"cust-gen-{n}", archetype, partner_since=random.randint(2018, 2024))
        print(f"-- {customer['name']} ({customer['segment']}, {customer['renewal_rate_pct']}% renewal)")
        history = gen_discount_history(customer["id"], archetype, customer["partner_since"])
        deal = gen_deal(f"deal-gen-{n}", customer)
        for h in history:
            print(f"--   {h['date']}: {h['discount_pct']}% ({h['outcome']})")
        print(f"--   Deal: {deal['name']} [{', '.join(deal['product_categories'])}, {deal['term_length']}, {deal['region']}]")
        print()
